import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";

const inter = Inter({
 subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that wraps the application with tRPC provider, global font, and styling.
 *
 * Renders the application's children inside an HTML structure with the Inter font and antialiasing, and provides tRPC context to all descendants.
 *
 * @param children - The content to be rendered within the layout
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider> 
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
      >
        {children}
      </body>
    </html>
    </TRPCReactProvider>
  );
}
